name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Test on OTP ${{ matrix.otp }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp: ['22.3', '23.3', '24.1', '24.2']
        rebar3: ['3.17.0', '3.18.0']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: ${{matrix.rebar3}}
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit
