name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [22.3, 23.3, 24.1, 24.2]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.1.3
      with:
        otp-version: ${{ matrix.otp_version }}
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit
